{
 "title": "service_telegrambot",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "ОСНОВНЫЕ ПОКАЗАТЕЛИ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "• Всего пользователей:",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (user_id)(count_over_time({service=\"telegrambot\",job=\"docker\"}|json|user_id!=\"\"[30d])))"
    }
   ]
  },
  {
   "title": "• Активных сегодня:",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (user_id)(count_over_time({service=\"telegrambot\",job=\"docker\"}|json|user_id!=\"\"[24h])))"
    }
   ]
  },
  {
   "title": "• Всего Новичков сегодня:",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (user_id)(count_over_time({service=\"telegrambot\",job=\"docker\"}|json|event=~\"start_command|start_from_site\"[24h])))"
    }
   ]
  },
  {
   "title": "• Поисковых запросов:",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=\"telegrambot\",job=\"docker\"}|json|event=\"estate_search\"[24h]))"
    }
   ]
  },
  {
   "title": "• % кто сделал что-то:",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(count(sum by(user_id)(count_over_time({service=\"telegrambot\",job=\"docker\"}|json|event=\"estate_search\"[24h]))) / count(sum by(user_id)(count_over_time({service=\"telegrambot\",job=\"docker\"}|json|user_id!=\"\"[24h]))))*100"
    }
   ]
  },
  {
   "title": "• % Новых с сайта сегодня:",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(count(sum by(user_id)(count_over_time({service=\"telegrambot\",job=\"docker\"}|json|event=\"start_from_site\"[24h]))) / count(sum by(user_id)(count_over_time({service=\"telegrambot\",job=\"docker\"}|json|event=~\"start_command|start_from_site\"[24h]))))*100"
    }
   ]
  },
  { "title": "СПИСКИ ПОЛЬЗОВАТЕЛЕЙ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "1) Все пользователи",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{service=\"telegrambot\",job=\"docker\"} | json | user_id!=\"\" | line_format \"{{.user_id}}\" | dedup"
    }
   ]
  },
  {
   "title": "2) Новички сегодня",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum by (user_id, username)(count_over_time({service=\"telegrambot\",job=\"docker\"}|json|event=~\"start_command|start_from_site\"[24h]))"
    }
   ]
  },
  {
   "title": "3) Активные сегодня",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum by (user_id, username)(count_over_time({service=\"telegrambot\",job=\"docker\"}|json|user_id!=\"\"[24h]))"
    }
   ]
  },
  { "title": "ПОПУЛЯРНОСТЬ ОБЪЕКТОВ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Все запросы по ЖК",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sort_desc(sum by (estate_id)(count_over_time({service=\"telegrambot\",job=\"docker\"}|json|event=\"estate_search\"[24h])))"
    }
   ]
  }
 ]
}