[server]
# domain = test.lotsmen.ru
domain = localhost
# root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
root_url = %(protocol)s://%(domain)s:%(http_port)s/
# serve_from_sub_path = true
serve_from_sub_path = false

[paths]
plugins = /etc/grafana/plugins


[security]
cookie_secure = false