{
 "title": "30 - CPU_MEM_DISK(time)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "app",
    "query": "label_values(service_wall:status, app)"
   },
   {
    "name": "service",
    "query": "label_values(service_wall:status{app=\"$app\"}, service)"
   },
   {
    "name": "env",
    "query": "label_values(service_wall:status{app=\"$app\",service=\"$service\"}, env)"
   },
   {
    "name": "version",
    "query": "label_values(service_wall:status{app=\"$app\",service=\"$service\",env=\"$env\"}, version)"
   }
  ]
 },
 "panels": [
  {
   "title": "STATUS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_wall:status{app=\"$app\",service=\"$service\",env=\"$env\",version=\"$version\"}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "service_wall:cpu_pct{app=\"$app\",service=\"$service\",env=\"$env\",version=\"$version\"}"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "service_wall:mem_pct{app=\"$app\",service=\"$service\",env=\"$env\",version=\"$version\"}"
    }
   ]
  },
  {
   "title": "Disk Free %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "service_wall:disk_free_pct{app=\"$app\",service=\"$service\",env=\"$env\",version=\"$version\"}"
    }
   ]
  }
 ]
}